use anyhow::{Result, anyhow};
use indexmap::IndexMap;
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::{
    character_mod::character::CharacterKind,
    character_mod::effect::EffectParam,
    character_mod::stats::Stats,
    common::{
        constants::all_target_const::{TARGET_ALLY, TARGET_ENNEMY},
        constants::reach_const::INDIVIDUAL,
        constants::stats_const::*,
    },
    utils::{self, get_random_nb},
};

#[derive(Default, Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct AtksInfo {
    pub atk_name: String,
    pub nb_use: i64,
    pub totals_by_target: IndexMap<String, AccumulatedAtkInfo>, // key target, i64 dmg
}

#[derive(Default, Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct AccumulatedAtkInfo {
    pub total_full_heal: i64,
    pub total_full_dmg: i64,
    pub total_real_heal: i64,
    pub total_real_dmg: i64,
}

#[derive(Debug, Clone, PartialEq)]
pub struct LauncherAtkInfo {
    pub id_name: String,
    pub kind: CharacterKind,
    pub stats: Stats,
    pub atk_type: AttackType,
}

/// Defines the parameters of an attack.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
#[serde(default)]
pub struct AttackType {
    /// Name of the attack
    #[serde(rename = "Nom")]
    pub name: String,
    /// Level of the attack
    #[serde(rename = "Niveau")]
    pub level: u64,
    /// Mana cost of the attack
    #[serde(rename = "Coût de mana")]
    pub mana_cost: u64,
    /// Vigor cost of the attack
    #[serde(rename = "Coût de vigueur")]
    pub vigor_cost: u64,
    /// Berserk cost of the attack
    #[serde(rename = "Coût de rage")]
    pub berseck_cost: u64,
    /// Target of the attack, can be TARGET_ALLY, TARGET_ENNEMY, TARGET_HIMSELF, TARGET_ONLY_ALLY
    #[serde(rename = "Cible")]
    pub target: String,
    /// Reach of the attack, can be INDIVIDUAL, ZONE, ALL
    #[serde(rename = "Portée")]
    pub reach: String,
    /// Photo name of the attack
    #[serde(rename = "Photo")]
    pub name_photo: String,
    /// All effects of the attack
    #[serde(rename = "Effet")]
    pub all_effects: Vec<EffectParam>,
    /// Aggro generated by that attack
    #[serde(rename = "Aggro")]
    pub aggro: i64,
    /// Whether the attack can be launched or not
    #[serde(rename = "CanBeLaunched")]
    pub can_be_launched: bool,
    /// Optional description of the attack, shown as a tooltip in the UI
    #[serde(rename = "Description", default)]
    pub description: String,
    /// Optional mechanical summary of the attack's effects, shown as a tooltip in the UI
    #[serde(rename = "DescriptionEffects", default)]
    pub effects_description: String,
}

impl Default for AttackType {
    fn default() -> Self {
        AttackType {
            name: "".to_owned(),
            level: 0,
            mana_cost: 0,
            vigor_cost: 0,
            berseck_cost: 0,
            target: TARGET_ALLY.to_owned(),
            reach: INDIVIDUAL.to_owned(),
            name_photo: "".to_owned(),
            all_effects: vec![],
            aggro: 0,
            can_be_launched: true,
            description: "".to_owned(),
            effects_description: "".to_owned(),
        }
    }
}

impl AttackType {
    /// Try to create an AttackType from a JSON file
    pub fn try_new_from_json<P: AsRef<Path>>(path: P) -> Result<AttackType> {
        utils::read_from_json::<_, AttackType>(&path)
            .map_err(|_| anyhow!("Unknown file: {:?}", path.as_ref()))
    }

    /// Check if the attack has only heal effects
    pub fn has_only_heal_effect(&self) -> bool {
        let mut is_only_heal_effect = false;
        for e in &self.all_effects {
            if e.buffer.stats_name == HP && e.buffer.value < 0 {
                return false;
            }
            if e.buffer.stats_name == HP && e.buffer.value > 0 {
                is_only_heal_effect = true;
            }
        }
        if self.target != TARGET_ENNEMY && is_only_heal_effect {
            return true;
        }
        false
    }

    /// Get one random attack name from a list of attacks
    pub fn get_one_random_atk_name(launchable_atks: &[AttackType]) -> Option<String> {
        if launchable_atks.is_empty() {
            return None;
        }
        let nb = get_random_nb(0, launchable_atks.len() as i64 - 1);
        launchable_atks.get(nb as usize).map(|atk| atk.name.clone())
    }

    /// Armor mitigation constant. At this armor value, damage is halved.
    pub const ARMOR_FACTOR: f64 = 100.0;

    /// Power scaling divisor: launcher power contributes multiplicatively to damage.
    /// power_factor = 1 + launcher_pow / POWER_SCALE
    pub const POWER_SCALE: f64 = 100.0;

    /// Physical power contributes to defense with this divisor.
    /// defense = armor + target_phys_pow / DEFENSE_DIVISOR (physical only)
    pub const DEFENSE_DIVISOR: f64 = 4.0;

    /// Returns `(raw_damage, effective_damage)`:
    /// - `raw_damage`: damage before armor (attack value scaled by launcher power)
    /// - `effective_damage`: damage after armor mitigation (diminishing-returns formula)
    ///
    /// Both values are negative for damage, positive for healing.
    /// Returns `(0, 0)` if `nb_of_turns <= 0` to avoid division by zero.
    pub fn damage_by_atk(
        target_stats: &Stats,
        launcher_stats: &Stats,
        is_magic: bool,
        atk_value: i64,
        nb_of_turns: i64,
    ) -> (i64, i64) {
        if nb_of_turns <= 0 {
            return (0, 0);
        }
        let target_armor = target_stats.get_armor_stat(is_magic);
        let target_power = target_stats.get_power_stat(is_magic);
        let launcher_pow = launcher_stats.get_power_stat(is_magic);

        // Multiplicative power scaling: higher launcher power amplifies the base attack value.
        let power_factor = 1.0 + launcher_pow as f64 / Self::POWER_SCALE;
        let raw_damage = (atk_value as f64 * power_factor).round() as i64;

        // Defense = armor + target power contribution (physical resistance from strength).
        let defense = target_armor as f64 + target_power as f64 / Self::DEFENSE_DIVISOR;
        let protection = Self::ARMOR_FACTOR / (Self::ARMOR_FACTOR + defense);
        let effective_damage = (raw_damage as f64 * protection).round() as i64;

        (raw_damage, effective_damage)
    }
}

#[cfg(test)]
mod tests {
    use indexmap::IndexMap;

    use crate::{
        character_mod::{attack_type::AttackType, buffers::BufKinds, stats::Stats},
        common::constants::{
            all_target_const::TARGET_ENNEMY, reach_const::INDIVIDUAL, stats_const::*,
        },
        testing::testing_atk::{build_atk_damage_indiv, build_atk_heal1_indiv},
    };

    #[test]
    fn unit_try_new_from_json() {
        // existence
        let file_path = "./tests/offlines/attack/test/hehe.json"; // Path to the JSON file
        let atk_type = AttackType::try_new_from_json(file_path);
        assert!(atk_type.is_err());

        let file_path = "./tests/offlines/attack/test/SimpleAtk.json"; // Path to the JSON file
        let atk_type = AttackType::try_new_from_json(file_path);
        assert!(atk_type.is_ok());
        let atk_type: AttackType = atk_type.unwrap();
        assert_eq!(atk_type.name, "SimpleAtk");
        assert_eq!(atk_type.level, 1);
        assert_eq!(atk_type.mana_cost, 0);
        assert_eq!(atk_type.vigor_cost, 9);
        assert_eq!(atk_type.berseck_cost, 0);
        assert_eq!(atk_type.target, TARGET_ENNEMY);
        assert_eq!(atk_type.reach, INDIVIDUAL);
        assert_eq!(atk_type.name_photo, "SimpleAtk.png");
        assert_eq!(atk_type.aggro, 0);
        // decode the effect
        assert_eq!(atk_type.all_effects.len(), 1);
        assert_eq!(atk_type.all_effects[0].buffer.stats_name, HP);
        assert_eq!(atk_type.all_effects[0].buffer.value, -35);
        assert_eq!(atk_type.all_effects[0].target_kind, TARGET_ENNEMY);
        assert_eq!(atk_type.all_effects[0].reach, INDIVIDUAL);
        assert_eq!(
            atk_type.all_effects[0].buffer.kind,
            BufKinds::ChangeCurrentStatByValue
        );
        assert_eq!(atk_type.all_effects[0].sub_value_effect, 0);
    }

    #[test]
    fn unit_has_only_heal_effect() {
        let atk_dmg = build_atk_damage_indiv();
        assert!(!atk_dmg.has_only_heal_effect());

        let mut atk_heal = build_atk_heal1_indiv();
        assert!(atk_heal.has_only_heal_effect());

        atk_heal.target = TARGET_ENNEMY.to_owned();
        assert!(!atk_heal.has_only_heal_effect());
    }

    #[test]
    fn unit_get_one_random_atk_name() {
        let atk1 = build_atk_damage_indiv();
        let atk2 = build_atk_heal1_indiv();
        let mut all_atks = IndexMap::new();
        all_atks.insert(atk1.name.clone(), atk1.clone());
        all_atks.insert(atk2.name.clone(), atk2.clone());

        let random_atk_name =
            AttackType::get_one_random_atk_name(&all_atks.values().cloned().collect::<Vec<_>>());
        assert!(random_atk_name.is_some());
        let atk_name = random_atk_name.unwrap();
        assert!(atk_name == atk1.name || atk_name == atk2.name);

        let empty_atks: IndexMap<String, AttackType> = IndexMap::new();
        let random_atk_name =
            AttackType::get_one_random_atk_name(&empty_atks.values().cloned().collect::<Vec<_>>());
        assert!(random_atk_name.is_none());
    }

    #[test]
    fn unit_damage_by_atk() {
        let mut target_stats = Stats::default();
        target_stats.init();
        target_stats.get_mut_value(MAGICAL_ARMOR).current = 10;
        // target magical power contributes to defense
        target_stats.get_mut_value(MAGICAL_POWER).current = 20;

        let mut launcher_stats = Stats::default();
        launcher_stats.init();
        launcher_stats.get_mut_value(MAGICAL_POWER).current = 100;

        // power_factor = 1 + 100/100 = 2.0; raw = round(-35 * 2.0) = -70
        // defense = 10 + 20/4 = 15; protection = 100/115 ≈ 0.8696
        // effective = round(-70 * 0.8696) = round(-60.87) = -61
        let (raw, effective) =
            AttackType::damage_by_atk(&target_stats, &launcher_stats, true, -35, 1);
        assert_eq!(raw, -70);
        assert_eq!(effective, -61);

        // nb_of_turns = 0 → (0, 0) to avoid division by zero
        let (raw0, eff0) = AttackType::damage_by_atk(&target_stats, &launcher_stats, true, -35, 0);
        assert_eq!(raw0, 0);
        assert_eq!(eff0, 0);

        // launcher_pow = 0: power_factor = 1.0; raw = atk_value unchanged
        let mut launcher_zero = Stats::default();
        launcher_zero.init();
        let (raw_z, _) = AttackType::damage_by_atk(&target_stats, &launcher_zero, true, -50, 1);
        assert_eq!(raw_z, -50);
    }
}
